### ISSUE TITLE
Typedef set causes an error

### ISSUE THREAD

**Issue by dantswain** [pinterest/elixir-thrift#111]
The following thrift snippet:

```
  typedef set<i32> SetOfIntegers

  struct Thangs {
    1: optional SetOfIntegers magic_numbers
  }
```

Causes the following error on `mix thrift.generate`:

```
** (exit) an exception was raised:
    ** (CaseClauseError) no case clause matching: {:set, :i32}
        (thrift) lib/thrift/parser/resolver.ex:37: anonymous fn/2 in Thrift.Parser.Resolver.update/3
        (elixir) lib/map.ex:114: Map.do_new_transform/3
        (thrift) lib/thrift/parser/resolver.ex:36: Thrift.Parser.Resolver.update/3
        (elixir) lib/agent/server.ex:23: Agent.Server.handle_call/3
        (stdlib) gen_server.erl:615: :gen_server.try_handle_call/4
        (stdlib) gen_server.erl:647: :gen_server.handle_msg/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by dantswain** [comment]
Fixed by #118 :tada:
