### ISSUE TITLE
Generator should specify which file causes an error

### ISSUE THREAD

**Issue by dantswain** [pinterest/elixir-thrift#112]
Running `mix thrift.generate` with a directory that has a bunch of thrift files in it, I get this error:

```
** (MatchError) no match of right hand side value: {:error, {32, :thrift_parser, ['syntax error before: ', '\']\'']}}
    lib/thrift/parser.ex:19: Thrift.Parser.parse/1
    lib/thrift/parser/parsed_file.ex:13: Thrift.Parser.ParsedFile.new/1
    lib/thrift/parser.ex:57: Thrift.Parser.parse_file/1
    lib/thrift/generator.ex:11: Thrift.Generator.generate!/2
    lib/mix/tasks/thrift.generate.ex:32: anonymous fn/3 in Mix.Tasks.Thrift.Generate.run/1
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/thrift.generate.ex:31: Mix.Tasks.Thrift.Generate.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
```

I don't think any of my files have thrift syntax errors, which is another issue that I'll try to track down, but this doesn't tell me which file is causing the error.

**Comment by dantswain** [comment]
Closed by #128
