### ISSUE TITLE
Set of typedefed type causes parse error

### ISSUE THREAD

**Issue by dantswain** [pinterest/elixir-thrift#120]
Can be reproduced by changing this case in models_test.exs

```
  @thrift_file name: "complex_typedefs.thrift", contents: """
  typedef Stuff i32
  typedef set<i32> IntSet
  struct Thangs {
    1: optional IntSet numbers,
    2: optional set<Stuff> set_of_stuff
  }
  """
```

Then running mix test results in

```
** (MatchError) no match of right hand side value: {:error, {2, :thrift_parser, ['syntax error before: ', 'i32']}}
    (thrift) lib/thrift/parser.ex:20: Thrift.Parser.parse/1
    (thrift) lib/thrift/parser/parsed_file.ex:13: Thrift.Parser.ParsedFile.new/1
    (thrift) lib/thrift/parser.ex:60: Thrift.Parser.parse_file/1
    (thrift) lib/thrift/generator.ex:11: Thrift.Generator.generate!/2
    (elixir) lib/enum.ex:925: anonymous fn/3 in Enum.flat_map/2
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:924: Enum.flat_map/2
    (thrift) test/support/lib/thrift_test_case.ex:47: ThriftTestCase.compile_and_build_erlang_helpers/2
    (thrift) expanding macro: ThriftTestCase.__before_compile__/1
    test/generator/models_test.exs:1: Thrift.Generator.ModelsTest (module)
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:57: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5
```

**Comment by dantswain** [comment]
Cannot reproduce.  My example has `typedef Stuff i32` which should be `typedef i32 Stuff` but I know I had this problem "in the wild".  Appears to be fixed now anyways, so :tada:
