### ISSUE TITLE
Const default values fail to generate

### ISSUE THREAD

**Issue by dantswain** [pinterest/elixir-thrift#140]
Example thrift:

```
  const string DefaultRootPassword = "abc123"

  struct BestPracticeSecurity {
    1: optional string root_password = DefaultRootPassword
  }
```

Results in

```
** (MatchError) no match of right hand side value: [:DefaultRootPassword]
    (thrift) lib/thrift/parser/models.ex:105: Thrift.Parser.Models.TEnumValue.new/1
    (thrift) src/thrift_parser.yrl:132: :thrift_parser.yeccpars2_76/7
    (thrift) /usr/local/Cellar/erlang/19.1/lib/erlang/lib/parsetools-2.1.3/include/yeccpre.hrl:57: :thrift_parser.yeccpars0/5
    (thrift) lib/thrift/parser/parsed_file.ex:12: Thrift.Parser.ParsedFile.new/1
    (thrift) lib/thrift/parser.ex:61: Thrift.Parser.parse_file/1
    (thrift) lib/thrift/generator.ex:39: Thrift.Generator.generate!/2
    (elixir) lib/enum.ex:925: anonymous fn/3 in Enum.flat_map/2
    (elixir) lib/enum.ex:1623: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:924: Enum.flat_map/2
    (thrift) test/support/lib/thrift_test_case.ex:47: ThriftTestCase.compile_and_build_erlang_helpers/2
    (thrift) expanding macro: ThriftTestCase.__before_compile__/1
    test/generator/models_test.exs:1: Thrift.Generator.ModelsTest (module)
    (elixir) lib/code.ex:363: Code.require_file/2
    (elixir) lib/kernel/parallel_require.ex:57: anonymous fn/2 in Kernel.ParallelRequire.spawn_requires/5

```

**Comment by pguillory** [comment]
Should be fixed.
