### ISSUE TITLE
Included enums not being resolved correctly

### ISSUE THREAD

**Issue by dantswain** [pinterest/elixir-thrift#268]
Updating to the most recent thrift_tng commit breaks some of our existing (working) code.  The following test case is distilled down from something in our working thrift IDL files, so if the test is incorrect then I've done a bad job trying to simplify.

```
  @thrift_file name: "numbers.thrift", contents: """
  enum Number {
    ZERO = 0,
    ONE = 1,
    TWO = 2,
    THREE = 3
  }
  """

  @thrift_file name: "includes_enum.thrift", contents: """
  include "numbers.thrift"

  struct Person {
    1: optional Number favoriteNumber = Number.ZERO
  }
  """

  thrift_test "including an emum" do
    assert %Person{farvorite_number: 0} == %Person{}
  end
```

Results in

```
elixir-thrift - thrift_tng! ❯ mix test test/thrift/generator/binary_protocol_test.exs
Excluding tags: [pending: true]

** (RuntimeError) Fatal error: Could not find value: Number.ZERO
    (thrift) lib/thrift/generator/utils.ex:279: Thrift.Generator.Utils.resolution_failed/1
    (thrift) lib/thrift/generator/utils.ex:186: Thrift.Generator.Utils.quote_value/3
    (thrift) lib/thrift/generator/struct_generator.ex:16: anonymous fn/2 in Thrift.Generator.StructGenerator.generate/4
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    (thrift) lib/thrift/generator/struct_generator.ex:14: Thrift.Generator.StructGenerator.generate/4
    (thrift) lib/thrift/generator.ex:181: anonymous fn/3 in Thrift.Generator.generate_struct_modules/1
    (stdlib) lists.erl:1263: :lists.foldl/3
    (thrift) lib/thrift/generator.ex:179: Thrift.Generator.generate_struct_modules/1
    (thrift) lib/thrift/generator.ex:75: Thrift.Generator.generate_schema/1
    (thrift) lib/thrift/generator.ex:52: anonymous fn/3 in Thrift.Generator.generate!/2
    (elixir) lib/enum.ex:958: anonymous fn/3 in Enum.flat_map/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (elixir) lib/enum.ex:1772: Enum.flat_map/2
    (elixir) lib/enum.ex:966: Enum.flat_map_list/2
    (elixir) lib/enum.ex:967: Enum.flat_map_list/2
    (thrift) test/support/lib/thrift_test_case.ex:97: ThriftTestCase.generate_elixir_files/3
    (thrift) test/support/lib/thrift_test_case.ex:84: ThriftTestCase.generate_files/4
    (thrift) test/support/lib/thrift_test_case.ex:36: ThriftTestCase.quoted_contents/2
    test/thrift/generator/binary_protocol_test.exs:658: (module)

```

**Comment by dantswain** [comment]
Not sure I made it clear in the original description, but this is something that broke recently.  As of commit 359d70a1cbfe1d7d4388750c8286552b22cf759d this was working.

**Comment by joshuawscott** [comment]
I think this is related, as of https://github.com/pinterest/elixir-thrift/commit/ab561e25584aae78d5fc0fe25d95d3c1ae4ee8ae I'm getting a failure. Example thrift files:
`additions.thrift:`
```
enum ChocolateAdditionsType {
  ALMONDS = 1
}

typedef set<ChocolateAdditionsType> ChocolateAdditions
```
`chocolate.thrift:`
```
include "additions.thrift"

struct Chocolate {
  1: optional additions.ChocolateAdditions extra_stuff
}
```
Adding those to `test/fixtures/app/thrift/` gets 6 failures, all with this similar stacktrace:
```
  6) test cleaning generated files (Mix.Tasks.Compile.ThriftTest)
     test/mix/tasks/compile.thrift_test.exs:57
     ** (FunctionClauseError) no function clause matching in Thrift.Protocol.Binary.Type.of/1
     stacktrace:
       (thrift) lib/thrift/protocol/binary/type.ex:21: Thrift.Protocol.Binary.Type.of(nil)
       (thrift) lib/thrift/generator/struct_binary_protocol.ex:864: Thrift.Generator.StructBinaryProtocol.value_serializer/3
       (thrift) lib/thrift/generator/struct_binary_protocol.ex:824: Thrift.Generator.StructBinaryProtocol.required_field_serializer/2
       (thrift) lib/thrift/generator/struct_binary_protocol.ex:815: Thrift.Generator.StructBinaryProtocol.field_serializer/3
       (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
       (thrift) lib/thrift/generator/struct_binary_protocol.ex:761: Thrift.Generator.StructBinaryProtocol.struct_serializer/3
       (thrift) lib/thrift/generator/struct_generator.ex:20: Thrift.Generator.StructGenerator.generate/4
       (thrift) lib/thrift/generator.ex:181: anonymous fn/3 in Thrift.Generator.generate_struct_modules/1
       (stdlib) lists.erl:1263: :lists.foldl/3
       (thrift) lib/thrift/generator.ex:179: Thrift.Generator.generate_struct_modules/1
       (thrift) lib/thrift/generator.ex:75: Thrift.Generator.generate_schema/1
       (thrift) lib/thrift/generator.ex:27: anonymous fn/2 in Thrift.Generator.targets/1
       (elixir) lib/enum.ex:958: anonymous fn/3 in Enum.flat_map/2
       (stdlib) lists.erl:1263: :lists.foldl/3
       (elixir) lib/enum.ex:1772: Enum.flat_map/2
       (thrift) lib/mix/tasks/compile.thrift.ex:92: anonymous fn/4 in Mix.Tasks.Compile.Thrift.extract_targets/3
       (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
       (thrift) lib/mix/tasks/compile.thrift.ex:89: Mix.Tasks.Compile.Thrift.extract_targets/3
       (thrift) lib/mix/tasks/compile.thrift.ex:55: Mix.Tasks.Compile.Thrift.run/1
       (ex_unit) lib/ex_unit/capture_io.ex:146: ExUnit.CaptureIO.do_capture_io/2
```
