### ISSUE TITLE
Enumerations that use reserved keywords can generate uncompilable code

### ISSUE THREAD

**Issue by thecodeboss** [pinterest/elixir-thrift#294]
This thrift schema:
```thrift
enum Operator {
  AND = 0
}
```
generates an `Operator` module containing this invalid code:
```elixir
defmacro(and) do
  0
end
```
`and` is a reserved keyword in Elixir and hence we get this compile error:
```elixir
== Compilation error in file lib/thrift/generated/operator.ex ==
** (SyntaxError) lib/thrift/generated/operator.ex:3: syntax error before: 'and'
    (elixir) lib/kernel/parallel_compiler.ex:121: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by nichochar** [comment]
Great job @thecodeboss !
